### ISSUE TITLE
Ideas about a project roadmap

### ISSUE THREAD

**Issue by Cactucs** [manGoweb/mango-cli#160]
# Ideas
- [ ] Move to webpack
- [ ] Support react server rendering
- [x] Somehow deal with backwards/forwards compatibility and versioning

**Comment by honzasladek** [comment]
- [ ] never build on live server but move to CI instead :)

**Comment by ViliamKopecky** [comment]
For server react rendering probably choose some existing options like next.js
